"project_id": "795754"
"base_path": "."
"base_url": "https://api.crowdin.com"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

"auto_upload": true
"auto_download": true
"push_translations": false
"create_pull_request": false

files:
  - source: "/crowdin/en.json"
    translation: "/crowdin/%locale%.json"
