"project_id": "795754"
"base_path": "."
"base_url": "https://api.crowdin.com"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"preserve_hierarchy": true

files:
  - source: "/crowdin/en.json"
    translation: "/crowdin/%locale%.json"
