project_id: '795754'
auto_upload: 1
auto_download: 1
push_translations: 1
create_pull_request: 1
branch_name: l10n_crowdin_translations
pull_request_base_branch: main
pull_request_translation_completion: '100'
update_option: update_as_unapproved
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
commit_message: 'chore(l10n): update translations from Crowdin'
pull_request_title: [TL] Crowdin Translations Update
files:
  - source: /l10n/en.json
    translation: /l10n/%locale%.json
